language: node_js

os:
  - linux

node_js:
  - 10

cache: npm

before_install:
  - node --version

script:
  - npm run test
  - npm run build-storybook

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    tag: next
    on:
      tags: true
      repo: edekadigital/backoffice-ui
      node: 10
      condition: '$TRAVIS_OS_NAME = linux'
  - provider: pages
    local_dir: public
    target_branch: gh-pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: true
    on:
      branch: release/2.0.0
